### ISSUE TITLE
why no live server 😭

### ISSUE THREAD

**Issue by Shishir3D** [Rooneyish/odin-library#1]
# Turn on `github pages` 

Downloading ur project to view the website takes too much work :upside_down_face:

**Comment by Rooneyish** [comment]
Kun wala recent?

**Comment by Shishir3D** [comment]
yes yes

[library](https://rooneyish.github.io/odin-library/) wala ko live server thiyaena :exploding_head: 


![image](https://github.com/Rooneyish/odin-library/assets/66148659/35b160cd-36b0-4a02-bee6-abddbd26926e)

**Comment by Rooneyish** [comment]
> yes yes
> 
> [library](https://rooneyish.github.io/odin-library/) wala ko live server thiyaena 🤯
> 
> ![image](https://private-user-images.githubusercontent.com/66148659/342208388-35b160cd-36b0-4a02-bee6-abddbd26926e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMDk3NzMsIm5iZiI6MTcxOTIwOTQ3MywicGF0aCI6Ii82NjE0ODY1OS8zNDIyMDgzODgtMzViMTYwY2QtMzZiMC00YTAyLWJlZTYtYWJkZGJkMjY5MjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDA2MTExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NGUzZmVkYTE1ODFhNTU5OWRkMDc2ZWNkODhjYjFjOTdiNjRlOTkwOGMwYTM0NjdmYWU1YTVjOGEzZDk2N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._TpuX3SCR0OEfrs6mjzR7MvwQwMogNMWMDgWfnBRHeY)

k vo????
